// Generated by scripts/build-remix-assets.mjs — do not edit by hand.
// Maps logical asset names to their content-fingerprinted hrefs. Committed so
// the app layer (client-entries.ts, document.tsx) stays importable without a
// prior asset build; `pnpm remix:assets` rewrites it.
export const ASSET_MANIFEST: Record<string, string> = {
  "boot": "/assets/entries/boot-FEKTF5XB.js",
  "code-highlight.css": "/assets/code-highlight-e2f9f068.css",
  "enhance": "/assets/entries/enhance-PJHD2U7B.js",
  "page-stats": "/assets/entries/page-stats-LFLS4LLO.js",
  "share-links": "/assets/entries/share-links-T3QIINDD.js",
  "styles.css": "/assets/styles-412b2793.css",
  "theme-toggle": "/assets/entries/theme-toggle-ILFGFSWD.js"
};
