// Generated by scripts/generate-cache-digests.mjs — do not edit.
// Per-path content digests: document ETags, inner cache keys, and the
// post-deploy reconcile diff all read from here.

/** Digest of the shared code and styles, folded into every path digest. */
export const BUILD_DIGEST = "d705bd8abb4576c1";

/** Rendered document paths → digest of everything that page renders from. */
export const PATH_DIGESTS: Readonly<Record<string, string>> = {
  "/": "5c9f9e70048dc0b2",
  "/bdo-to-pagibig-refinancing/": "ed89ea8c55416360",
  "/converge-gpon-sfp-stick-mikrotik/": "a14942f1d7c4f12b",
  "/encrypted-dns-stable-resolver-mikrotik/": "3063624b24cdda63",
  "/mikrotik-home-network/": "ea09e965e48edbf1",
  "/mikrotik-ipv6-failover-bgp-bfd/": "e206fcad180aa472",
  "/mikrotik-ipv6-failover-bgp-bfd/chr/": "3b1e8a8acc1d960c",
  "/mikrotik-ipv6-failover-bgp-bfd/vyos/": "2c3eb8dd1b903759",
  "/mikrotik-per-vlan-ipv6/": "f28e119d714fba11",
  "/mikrotik-vlan-guest-iot/": "f236e3b7523963b8",
  "/multi-homed-ipv6-cgnat-mikrotik/": "7232adaeab8cdd3d",
  "/net-metering-general-trias/": "2833766d23bb4cca",
  "/nev-mileage/": "9063683e291485a9",
  "/nev-mileage/full-report": "b99c38dd8c7f2fc5",
  "/route64-ipv6-cgnat-mikrotik/": "71efb507d2feb553",
  "/rss.xml": "5c9f9e70048dc0b2",
  "/sitemap.xml": "5c9f9e70048dc0b2",
  "/solar-application-lancaster/": "b8bed348422ce34c",
  "/solar-report/": "c9141186e5b9579e",
  "/solar-report/full-report": "7f080d2a4c8e8554",
  "/unifi-controller-routeros-containers-mikrotik/": "5743a2e254449975",
  "/vps-ipv6-cgnat-mikrotik/": "1ffea5afb6ff02a5",
  "/vps-ipv6-cgnat-mikrotik/chr/": "0f12bcae4d366e39",
  "/vps-ipv6-cgnat-mikrotik/vyos/": "920f14c6c3cc0d93",
};

/** Non-fingerprinted public/ files → digest of their bytes. */
export const ASSET_DIGESTS: Readonly<Record<string, string>> = {
  "/apple-touch-icon.png": "1e6081f6fb63643d",
  "/favicon.ico": "be9ede3407469a39",
  "/favicon.svg": "80d97a902cabca0d",
  "/mikrotik-home-network/og.png": "d5c72e968dd0225f",
  "/mikrotik-home-network/test-ipv6-run.png": "3beb717ad728523d",
  "/net-metering-docs/plant-parameter-form.pdf": "fc6612e161521625",
  "/net-metering-docs/qe-coc-application-form-1.1-solar.pdf": "85c75c646f6d2d07",
  "/net-metering-docs/qe-coc-application-form-1.pdf": "f2f1108de56880fb",
  "/net-metering-general-trias/og.png": "42ee6631fd989e8a",
  "/nev-mileage/data/phev_log.csv": "42fad86cd746fb13",
  "/nev-mileage/full-report.md": "1568702f56d156e0",
  "/nev-mileage/og-image.png": "01ea508e9e1e6b0a",
  "/og.png": "fc14f79e2618c9ca",
  "/robots.txt": "de62be9ed8fe605a",
  "/solar-application-docs/waiver-of-accountability.docx": "a6ed849bf1fed2da",
  "/solar-application-lancaster/og.png": "f37503a0e6d52d57",
  "/solar-report/data/solar_hourly_2025-12.csv": "9c25066a50b5d0bb",
  "/solar-report/data/solar_hourly_2026-01.csv": "ec50c93177e801eb",
  "/solar-report/data/solar_hourly_2026-02.csv": "2a0e1c76e1b5b009",
  "/solar-report/data/solar_hourly_2026-03.csv": "a78342dfe57b4044",
  "/solar-report/data/solar_hourly_2026-04.csv": "d3a85f21742c37de",
  "/solar-report/data/solar_hourly_2026-05.csv": "b5126decd0c40a8f",
  "/solar-report/data/solar_hourly_2026-06.csv": "a5f34d46848b04a0",
  "/solar-report/data/solar_hourly_2026-07.csv": "0d03544b179a3384",
  "/solar-report/data/solar_hourly_2026-08.csv": "512f01520d07d1eb",
  "/solar-report/full-report.md": "09415adb8177935b",
  "/solar-report/og-image.png": "3a6d485ce8e285d6",
};
