// Generated by scripts/generate-cache-digests.mjs — do not edit.
// Per-path content digests: document ETags, inner cache keys, and the
// post-deploy reconcile diff all read from here.

/** Digest of the shared code and styles, folded into every path digest. */
export const BUILD_DIGEST = "03871121837719d5";

/** Rendered document paths → digest of everything that page renders from. */
export const PATH_DIGESTS: Readonly<Record<string, string>> = {
  "/": "bdfdd34db9f43015",
  "/bdo-to-pagibig-refinancing/": "c9a8491477e796ba",
  "/converge-gpon-sfp-stick-mikrotik/": "fb1bc27d4e0891cf",
  "/encrypted-dns-stable-resolver-mikrotik/": "6568da963387b5b7",
  "/mikrotik-home-network/": "1913b0ccae0aceee",
  "/mikrotik-ipv6-failover-bgp-bfd/": "d5974f90396e29a7",
  "/mikrotik-ipv6-failover-bgp-bfd/chr/": "9beff0a067f387fb",
  "/mikrotik-ipv6-failover-bgp-bfd/vyos/": "8491786b936b3efb",
  "/mikrotik-per-vlan-ipv6/": "778183094dff4f04",
  "/mikrotik-vlan-guest-iot/": "85687a9cde1da6d6",
  "/multi-homed-ipv6-cgnat-mikrotik/": "de8b86171d4736f8",
  "/net-metering-general-trias/": "b08cc26482b74ec5",
  "/nev-mileage/": "1d12c064a2e6fc35",
  "/nev-mileage/full-report": "2799b941d174fa55",
  "/route64-ipv6-cgnat-mikrotik/": "05aa21de5da3d661",
  "/rss.xml": "bdfdd34db9f43015",
  "/sitemap.xml": "bdfdd34db9f43015",
  "/solar-application-lancaster/": "4f8d6e8f01d2fb5c",
  "/solar-report/": "480754f1866b877c",
  "/solar-report/full-report": "2a1e3ca693dc0a87",
  "/unifi-controller-routeros-containers-mikrotik/": "d930b999295451b2",
  "/vps-ipv6-cgnat-mikrotik/": "e32c7d1e221eebb1",
  "/vps-ipv6-cgnat-mikrotik/chr/": "85048756c02b7ffa",
  "/vps-ipv6-cgnat-mikrotik/vyos/": "abc8086f46a314a3",
};

/** Non-fingerprinted public/ files → digest of their bytes. */
export const ASSET_DIGESTS: Readonly<Record<string, string>> = {
  "/mikrotik-home-network/og.png": "d5c72e968dd0225f",
  "/mikrotik-home-network/test-ipv6-run.png": "3beb717ad728523d",
  "/net-metering-docs/plant-parameter-form.pdf": "fc6612e161521625",
  "/net-metering-docs/qe-coc-application-form-1.1-solar.pdf": "85c75c646f6d2d07",
  "/net-metering-docs/qe-coc-application-form-1.pdf": "f2f1108de56880fb",
  "/net-metering-general-trias/og.png": "42ee6631fd989e8a",
  "/nev-mileage/data/phev_log.csv": "42fad86cd746fb13",
  "/nev-mileage/full-report.md": "1568702f56d156e0",
  "/nev-mileage/og-image.png": "01ea508e9e1e6b0a",
  "/og.png": "fc14f79e2618c9ca",
  "/robots.txt": "de62be9ed8fe605a",
  "/solar-application-docs/waiver-of-accountability.docx": "a6ed849bf1fed2da",
  "/solar-application-lancaster/og.png": "f37503a0e6d52d57",
  "/solar-report/data/solar_hourly_2025-12.csv": "9c25066a50b5d0bb",
  "/solar-report/data/solar_hourly_2026-01.csv": "ec50c93177e801eb",
  "/solar-report/data/solar_hourly_2026-02.csv": "2a0e1c76e1b5b009",
  "/solar-report/data/solar_hourly_2026-03.csv": "a78342dfe57b4044",
  "/solar-report/data/solar_hourly_2026-04.csv": "d3a85f21742c37de",
  "/solar-report/data/solar_hourly_2026-05.csv": "b5126decd0c40a8f",
  "/solar-report/data/solar_hourly_2026-06.csv": "a5f34d46848b04a0",
  "/solar-report/data/solar_hourly_2026-07.csv": "0d03544b179a3384",
  "/solar-report/data/solar_hourly_2026-08.csv": "512f01520d07d1eb",
  "/solar-report/full-report.md": "09415adb8177935b",
  "/solar-report/og-image.png": "3a6d485ce8e285d6",
};
