// Generated by scripts/generate-cache-digests.mjs — do not edit.
// Per-path content digests: document ETags, inner cache keys, and the
// post-deploy reconcile diff all read from here.

/** Digest of the shared code and styles, folded into every path digest. */
export const BUILD_DIGEST = "0859c347168ad33d";

/** Rendered document paths → digest of everything that page renders from. */
export const PATH_DIGESTS: Readonly<Record<string, string>> = {
  "/": "bef419b50061f87e",
  "/bdo-to-pagibig-refinancing/": "ff50b8324b5101bc",
  "/converge-gpon-sfp-stick-mikrotik/": "a2affd0d2ff87fd7",
  "/encrypted-dns-stable-resolver-mikrotik/": "dd758c47599fbc49",
  "/mikrotik-home-network/": "af3cf4b18e536fff",
  "/mikrotik-ipv6-failover-bgp-bfd/": "e7f008f36955c783",
  "/mikrotik-ipv6-failover-bgp-bfd/chr/": "34dfbb4ca8e2a67b",
  "/mikrotik-ipv6-failover-bgp-bfd/vyos/": "16d6308b7b3e8df0",
  "/mikrotik-per-vlan-ipv6/": "5455e4542553c264",
  "/mikrotik-vlan-guest-iot/": "6ca129ed90038b48",
  "/multi-homed-ipv6-cgnat-mikrotik/": "f742d0f2adda073b",
  "/net-metering-general-trias/": "30ed836f858bc443",
  "/nev-mileage/": "11d3512da0eca1ca",
  "/nev-mileage/full-report": "13edd7ba1df7c302",
  "/route64-ipv6-cgnat-mikrotik/": "b4cf2de063761141",
  "/rss.xml": "bef419b50061f87e",
  "/sitemap.xml": "bef419b50061f87e",
  "/solar-application-lancaster/": "727e6e523aec0623",
  "/solar-report/": "0d5d8cf550d61be1",
  "/solar-report/full-report": "6b1f734ab7e71570",
  "/unifi-controller-routeros-containers-mikrotik/": "35fba4d689b921cf",
  "/vps-ipv6-cgnat-mikrotik/": "7c4a3cee3540d033",
  "/vps-ipv6-cgnat-mikrotik/chr/": "81b2c92bc641a48b",
  "/vps-ipv6-cgnat-mikrotik/vyos/": "c54e4831f6876c9e",
};

/** Non-fingerprinted public/ files → digest of their bytes. */
export const ASSET_DIGESTS: Readonly<Record<string, string>> = {
  "/mikrotik-home-network/og.png": "d5c72e968dd0225f",
  "/mikrotik-home-network/test-ipv6-run.png": "3beb717ad728523d",
  "/net-metering-docs/plant-parameter-form.pdf": "fc6612e161521625",
  "/net-metering-docs/qe-coc-application-form-1.1-solar.pdf": "85c75c646f6d2d07",
  "/net-metering-docs/qe-coc-application-form-1.pdf": "f2f1108de56880fb",
  "/net-metering-general-trias/og.png": "42ee6631fd989e8a",
  "/nev-mileage/data/phev_log.csv": "11e722d30d81abdc",
  "/nev-mileage/full-report.md": "6881d94afc00f0a7",
  "/nev-mileage/og-image.png": "c5d8b38df6088ec2",
  "/og.png": "fc14f79e2618c9ca",
  "/robots.txt": "de62be9ed8fe605a",
  "/solar-application-docs/waiver-of-accountability.docx": "a6ed849bf1fed2da",
  "/solar-application-lancaster/og.png": "f37503a0e6d52d57",
  "/solar-report/data/solar_hourly_2025-12.csv": "9c25066a50b5d0bb",
  "/solar-report/data/solar_hourly_2026-01.csv": "ec50c93177e801eb",
  "/solar-report/data/solar_hourly_2026-02.csv": "2a0e1c76e1b5b009",
  "/solar-report/data/solar_hourly_2026-03.csv": "a78342dfe57b4044",
  "/solar-report/data/solar_hourly_2026-04.csv": "d3a85f21742c37de",
  "/solar-report/data/solar_hourly_2026-05.csv": "b5126decd0c40a8f",
  "/solar-report/data/solar_hourly_2026-06.csv": "a5f34d46848b04a0",
  "/solar-report/full-report.md": "5dca11dc829467e8",
  "/solar-report/og-image.png": "ab7b3d99d079b6fb",
};
