// Generated by scripts/generate-remix-content.mjs — do not edit.
// Static text-module imports for Platform.content() on workerd.
import c0 from "../src/content/bdo-to-pagibig-refinancing.mdx";
import c1 from "../src/content/chr-mikrotik-ipv6-failover-bgp-bfd.mdx";
import c2 from "../src/content/chr-vps-ipv6-cgnat-mikrotik.mdx";
import c3 from "../src/content/converge-gpon-sfp-stick-mikrotik.mdx";
import c4 from "../src/content/encrypted-dns-stable-resolver-mikrotik.mdx";
import c5 from "../src/content/full-report.md";
import c6 from "../src/content/home-network-cgnat.mdx";
import c7 from "../src/content/mikrotik-ipv6-failover-bgp-bfd.mdx";
import c8 from "../src/content/mikrotik-per-vlan-ipv6.mdx";
import c9 from "../src/content/mikrotik-vlan-guest-iot.mdx";
import c10 from "../src/content/multi-homed-ipv6.mdx";
import c11 from "../src/content/net-metering.mdx";
import c12 from "../src/content/nev-full-report.md";
import c13 from "../src/content/nev-mileage-summary.mdx";
import c14 from "../src/content/route64-ipv6.mdx";
import c15 from "../src/content/solar-application-lancaster.mdx";
import c16 from "../src/content/solar-report-summary.mdx";
import c17 from "../src/content/unifi-controller-routeros-containers-mikrotik.mdx";
import c18 from "../src/content/vps-ipv6-cgnat-mikrotik.mdx";
import c19 from "../src/content/vyos-mikrotik-ipv6-failover-bgp-bfd.mdx";
import c20 from "../src/content/vyos-vps-ipv6-cgnat-mikrotik.mdx";

export const CONTENT: ReadonlyArray<[string, string]> = [
  ["bdo-to-pagibig-refinancing.mdx", c0],
  ["chr-mikrotik-ipv6-failover-bgp-bfd.mdx", c1],
  ["chr-vps-ipv6-cgnat-mikrotik.mdx", c2],
  ["converge-gpon-sfp-stick-mikrotik.mdx", c3],
  ["encrypted-dns-stable-resolver-mikrotik.mdx", c4],
  ["full-report.md", c5],
  ["home-network-cgnat.mdx", c6],
  ["mikrotik-ipv6-failover-bgp-bfd.mdx", c7],
  ["mikrotik-per-vlan-ipv6.mdx", c8],
  ["mikrotik-vlan-guest-iot.mdx", c9],
  ["multi-homed-ipv6.mdx", c10],
  ["net-metering.mdx", c11],
  ["nev-full-report.md", c12],
  ["nev-mileage-summary.mdx", c13],
  ["route64-ipv6.mdx", c14],
  ["solar-application-lancaster.mdx", c15],
  ["solar-report-summary.mdx", c16],
  ["unifi-controller-routeros-containers-mikrotik.mdx", c17],
  ["vps-ipv6-cgnat-mikrotik.mdx", c18],
  ["vyos-mikrotik-ipv6-failover-bgp-bfd.mdx", c19],
  ["vyos-vps-ipv6-cgnat-mikrotik.mdx", c20],
];
